version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 0753861857
      DB_NAME: fripperie
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0753861857
      POSTGRES_DB: fripperie
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork
    

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
