apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
  storageClassName: hostpath   

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: session-pvc
spec:
  accessModes:
    - ReadWriteMany  
  resources:
    requests:
      storage: 1Gi 
  storageClassName: hostpath  
